.travis.yml, REQUIRE, appveyor.yml, docs/make.jl, docs/src/man/constructing_tensors.md, src/Tensors.jl, src/constructors.jl, test/test_ad.jl, test/test_misc.jl
putting this branch here now instead
=> Fixes for Julia 0.6

src/Tensors.jl, src/constructors.jl, src/utilities.jl
more world fixes, now all generated functions are put last, so all utility functions are defined before them
=> more world fixes

src/Tensors.jl
this is a pretty sketchy method - replace with some inner constructors instead
=> Avoid defining convert from Function to NTuple

benchmark/benchmark_ad.jl, benchmark/benchmark_functions.jl, benchmark/runbenchmarks.jl
- clean up
- add some missing cases
- "pretty printing"
https://gist.github.com/fredrikekre/6fd9e2cededb71fcce907c0985757a3c
=> clean up benchmarks

src/simd.jl
```julia
AA3s = rand(SymmetricTensor{4, 3});
AA2s = rand(SymmetricTensor{4, 2});
A3 = rand(Tensor{2, 3});
```
PR:
```julia
julia> @btime $AA3s ⊡ $AA3s;
16.576 ns (0 allocations: 0 bytes)
julia> @btime $AA2s ⊡ $AA2s;
3.591 ns (0 allocations: 0 bytes)
julia> @btime $AA3s ⊡ $A3;
3.594 ns (0 allocations: 0 bytes)
```
master:
```julia
julia> @btime $AA3s ⊡ $AA3s;
45.887 ns (0 allocations: 0 bytes)
julia> @btime $AA2s ⊡ $AA2s;
4.305 ns (0 allocations: 0 bytes)
julia> @btime $AA3s ⊡ $A3;
8.526 ns (0 allocations: 0 bytes)
```
=> Some more simd-specializations

docs/make.jl
See https://travis-ci.org/KristofferC/Tensors.jl/jobs/214207279#L418
=> actually build docs

src/eigen.jl
`eigfact` returned tuple for isotropic case, so I fixed it to return `Eigen`. :)
=> Fix eigfact to return Eigen

src/basic_operations.jl, src/promotion_conversion.jl, src/simd.jl
https://gist.github.com/fredrikekre/6d84be3899b8a7d0e1d0f2688a2adac1
=> [WIP] simd promotions

src/constructors.jl
=> Fix zeros and ones

src/Tensors.jl, src/utilities.jl, src/voigt.jl, test/F64.jl, test/test_ad.jl, test/test_misc.jl, test/test_ops.jl
- Remove most `isa` tests and add type assertions instead
- check some more with `@inferred`
=> rewrite tests and define inplace versions of tovoigt

src/voigt.jl
I added `offset` keyword argument to `frommandel` function.
=> Add offset to frommandel

test/test_misc.jl
=> Add a test for diagonal tensors

src/automatic_differentiation.jl, test/test_ad.jl
Pretty cool, ref https://en.wikipedia.org/wiki/Vector_Laplacian
=> vector laplacian as a broadcasting operation

.travis.yml, REQUIRE, appveyor.yml, benchmark/benchmark_ad.jl, src/Tensors.jl, src/automatic_differentiation.jl, src/basic_operations.jl, src/constructors.jl, src/eigen.jl, src/math_ops.jl, src/promotion_conversion.jl, src/simd.jl, src/symmetric.jl, src/tensor_ops_errors.jl, src/tensor_products.jl, src/transpose.jl, src/utilities.jl, src/voigt.jl, test/F64.jl, test/REQUIRE, test/runtests.jl, test/test_ad.jl, test/test_misc.jl, test/test_ops.jl
=> wip 0.7 support, drop 0.6

REQUIRE, appveyor.yml, docs/make.jl, src/Tensors.jl, src/math_ops.jl, src/tensor_products.jl, test/F64.jl, test/runtests.jl
We should probably run a benchmark run vs 0.6 Tensors...
=> enable SIMD

src/Tensors.jl, test/test_misc.jl
Its pretty common that you just want to convert a tuple to a Vec.
=> define Vec on a tuple

docs/src/demos.md
This fixes a rendering problem.
=> fix syntax in math expression

src/automatic_differentiation.jl, test/test_ad.jl
Maybe a bit out of scope, but it's so little extra code and it's tangentially related so :man_shrugging:
=> Support AD for scalar -> scalar functions.

src/automatic_differentiation.jl
Tried to benchmark but its too fast... `current` is the one removed in this PR, `generated` the one added in this PR, and `function` this:
```julia
@inline function _extract_value_func(v::S) where {S<:Vec{<:Any,<:Dual}}
return get_base(S)(i -> @inbounds value(v[i]))
end
@inline function _extract_value_func(v::S) where {S<:SecondOrderTensor{<:Any,<:Dual}}
return get_base(S)((i,j) -> @inbounds value(v[i,j]))
end
```
|                   | Vec{1} | Vec{2} | Vec{3} | Tensor{2,1} | Tensor{2,2} | Tensor{2,3} | STensor{2,1} | STensor{2,2} | STensor{2,3} |
| ----------------- | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| compile current   | 0.005041 s (9.19 k allocs: 523.086 KiB) | 0.005821 s (13.36 k allocs: 731.894 KiB) | 0.006417 s (17.52 k allocs: 940.516 …
=> Simplify value extraction.

src/simd.jl
I don't think these should be needed now on newer LLVM versions.
=> get rid of some special cases no longer needed

src/voigt.jl, test/test_ops.jl
=> Solve #149, tomandel!

src/math_ops.jl, test/test_misc.jl
```julia
julia> typeof(normalize(rand(Vec{3})))
Vector{Float64} (alias for Array{Float64, 1})
julia> typeof(normalize(rand(Vec{3})))
Vec{3, Float64} (alias for Tensor{1, 3, Float64, 3})
```
=> Define LinearAlgebra.normalize(v::AbstractTensor)::typeof(v)

Project.toml, docs/Manifest.toml, src/Tensors.jl, src/precompile.jl
Benchmark (first time call):
```julia
function test()
for dim in (2, 3)
v = ones(Tensor{1, dim, Float64,})
σ = one(SymmetricTensor{2, dim, Float64})
F = one(Tensor{2, dim, Float64,})
E = one(SymmetricTensor{4, dim, Float64})
C = one(Tensor{4, dim, Float64,})
v * 1.0
v ⋅ v
v ⊗ v
σ ⋅ v
σ * 1.0
F ⋅ v
F * 1.0
σ ⊡ σ
F ⊡ F
E ⊡ σ
C ⊡ F
E * 1.0
C * 1.0
end
end
```
```julia
julia> @time @eval test()
0.108281 seconds (397.91 k allocations: 26.521 MiB, 177.42% compilation time)
julia> @time @eval test()
0.935148 seconds (3.00 M allocations: 203.775 MiB, 2.72% gc time, 186.47% compilation time)
```
These are the things that still compile even after this when running the function:
```julia
precompile(Tuple{SIMD.Intrinsics.var"##s8#111", Vararg{Any, 5}})
precompile(Tuple{typeof(Base.getindex), …
```
=> add a precompile workload

Project.toml
Fixes https://github.com/JuliaRegistries/General/pull/94521#issuecomment-1787836678
=> Add compat 1 to Statistics and LinearAlgebra
