- src/constructors.jl
This should fix #7 cc @andyferris
> fix evaluating one/zero in generator body

- src/math_ops.jl
Adding this, since that is almost 3 times faster than unrolling. For lower dimensions unrolling is still faster:
Unrolling:
```julia
julia> for dim in (1, 2, 3)
A = rand(Tensor{4, dim})
@btime norm($A);
end
2.030 ns (0 allocations: 0 bytes)
7.647 ns (0 allocations: 0 bytes)
58.132 ns (0 allocations: 0 bytes)
```
`mapreduce`:
```julia
julia> for dim in (1, 2, 3)
A = rand(Tensor{4, dim})
@btime norm($A);
end
4.155 ns (0 allocations: 0 bytes)
15.258 ns (0 allocations: 0 bytes)
23.076 ns (0 allocations: 0 bytes)
```
> Norm of Tensor{4, 3}

- src/constructors.jl
- test/F64.jl
- test/runtests.jl
- test/test_misc.jl
- test/test_ops.jl
This allows the "normal" methods to still be tested after the simd-forcing methods is introduced.
> Introduce a dummy type F64 to test with

- REQUIRE
- benchmark/runbenchmarks.jl
- src/Tensors.jl
- src/basic_operations.jl
- src/constructors.jl
- src/math_ops.jl
- src/simd.jl
- test/F64.jl
- test/test_ad.jl
This forces SIMD operations to be used even if julia is run with `-O2`.
TODO:
> [WIP] Simd operations

- src/simd.jl
```julia
julia> @btime dcontract($AAs, $As);
8.687 ns (0 allocations: 0 bytes)
julia> @btime dcontract2($AAs, $As);
4.578 ns (0 allocations: 0 bytes)
```
> simd method for dcontract(Sym4, Sym2)

- test/REQUIRE
- test/runtests.jl
- test/test_ad.jl
- test/test_misc.jl
- test/test_ops.jl
Need a tag to TimerOutputs to work:
Ex:
```
─────────────────────────────────────────────────────────────────────────────────────
Time                   Allocations      
──────────────────────   ───────────────────────
Tot / % measured:                155s / 91.9%           8.86GiB / 94.8%    
Section                      ncalls     time   %tot     avg     alloc   %tot      avg
─────────────────────────────────────────────────────────────────────────────────────
AD                                1    57.0s  40.0%   57.0s   4.86GiB  57.9%  4.86GiB
dim 3                           1    47.8s  33.5%   47.8s   4.40GiB  52.4%  4.40GiB
dim 2                           1    6.08s  4.26%   6.08s    311MiB  3.62%   311MiB
dim 1                           1    3.18s  2.23%   3.18s    160MiB  1.86% …
```
> add summary of time for tests

- src/basic_operations.jl
- src/constructors.jl
- src/math_ops.jl
- src/symmetric.jl
- src/tensor_ops_errors.jl
- src/tensor_products.jl
- src/transpose.jl
- src/utilities.jl
- test/test_ops.jl
> Simplify some functions

- src/math_ops.jl
- test/test_misc.jl
This PR is to support `inv` for fourth order tensors. This is useful in some computations of continuum mechanics. The definitions of inverse of fourth order tensors are follows:
```julia
julia> A = rand(Tensor{4,3});
julia> A ⊡ inv(A) ≈ one(Tensor{4,3})
true
julia> S = rand(SymmetricTensor{4,3});
julia> S ⊡ inv(S) ≈ one(SymmetricTensor{4,3})
true
```
> Add inv for fourth order tensors

- docs/src/man/other_operators.md
- src/math_ops.jl
- test/test_misc.jl
Currently `vol` function is the same as `trace`, but it is more useful to return tensor. This is consistent with `dev` function.
```julia
julia> A = rand(Tensor{2,3})
3×3 Tensors.Tensor{2,3,Float64,9}:
0.349248  0.383259    0.493558
0.327233  0.0432712   0.0638624
0.687384  0.00967807  0.654179
julia> vol(A) + dev(A) ≈ A
true
```
> Modify vol to return tensor

- src/Tensors.jl
- src/math_ops.jl
- src/voigt.jl
- test/test_ops.jl
I often use "Mandel" form to reduce the order of symmetric tensors because I don't need to care that the tensor is stress-like tensor or strain-like tensor. I think "Mandel" form is as popular as "Voigt" form, so it would be nice if this package has `tomandel` and `frommandel`.
> Add tomandel and frommandel

- src/transpose.jl
```jl
julia> ft(a, b) = a' ⋅ b
```
Before:
```jl
julia> @btime ft($A, $B);
18.635 ns (0 allocations: 0 bytes)
```
After:
```jl
julia> @btime ft($A, $B);
6.915 ns (0 allocations: 0 bytes)
```
Why these are not automatically inlined, I don't know...
> inline transpose wrappers

- src/Tensors.jl
- src/basic_operations.jl
- src/promotion_conversion.jl
Let things promote at the elementwise level instead.
Benchmark:
```jl
using Tensors
function u_ana{T}(x::Vec{2, T}) 
xs = (Vec{2}((-0.5,  0.5)),
Vec{2}((-0.5, -0.5)),
Vec{2}(( 0.5,  -0.5)))
σ = 1/8
s = zero(eltype(x))
for i in 1:3
s += exp(- norm(x - xs[i])^2 / σ^2)
end
return max(1e-15 * one(T), s) # Denormals, be gone
end
const ud2 = Tensors._load(rand(Vec{2}))
```
```
julia> @btime u_ana($ud2)
422.688 ns (12 allocations: 912 bytes)
```
```
julia> @btime u_ana($ud2)
87.265 ns (0 allocations: 0 bytes)
```
```
julia> @btime u_ana($ud2)
71.876 ns (0 allocations: 0 bytes)
```
> remove unnecessary promotions

- src/promotion_conversion.jl
fix #48 
Benchmarks:
```julia
using Tensors, BenchmarkTools
A = rand(Tensor{2, 3});
As = rand(SymmetricTensor{2, 3});
AA = rand(Tensor{4, 3});
AAs = rand(SymmetricTensor{4, 3});
@btime $A + $As;
@btime $AA + $AAs;
@btime convert(Tensor{2, 3}, $As);
@btime convert(Tensor{4, 3}, $AAs);
@btime Tensors.promote_base($A, $As);
@btime Tensors.promote_base($AA, $AAs);
@btime Tensors.promote($A, $As);
@btime Tensors.promote($AA, $AAs);
```
```
Master:    PR:
7.110 ns   3.464 ns
59.003 ns  30.983 ns
9.734 ns   3.256 ns
47.187 ns  33.929 ns
16.513 ns   4.142 ns
70.513 ns  43.951 ns
16.514 ns   4.141 ns
70.517 ns  43.962 ns
```
> inline some methods that where so previously

- src/basic_operations.jl
- test/test_misc.jl
This would be useful in some cases.
```julia
julia> t = rand(Tensor{2,3});
julia> t^0 ≈ one(t)
true
julia> t^1 ≈ t
true
julia> t^2 ≈ t ⋅ t
true
julia> t^3 ≈ t ⋅ t ⋅ t
true
julia> t^-1 ≈ inv(t)
true
```
> Add an integer power function for second order tensors

- src/basic_operations.jl
- test/test_misc.jl
use the new `literal_pow` on 0.6 and restrict to powers of -1, 0 and 1.
Note that the implementation on master is type-unstable for other powers when used with a `SymmetricTensor`.
Did you have a real use case for other powers @KeitaNakamura ?
> use literal pow on 0.6 and make power typestable on 0.5

- REQUIRE
since literal_pow wouldn't work before that, and new syntax like struct, where, etc
wouldn't work for very early 0.6.0-dev versions, would be better to use the 0.5-compatible
versions of the package for those julia versions
> set minimum julia version to 0.6.0-pre.alpha.108

- src/voigt.jl
Pre-PR:
```julia
julia> A = rand(SymmetricTensor{4,3});
julia> tovoigt(A);
julia> @time for i in 1:10000
tovoigt(A)
end
0.085385 seconds (1.01 M allocations: 19.896 MiB, 4.86% gc time)
```
PR:
```julia
julia> A = rand(SymmetricTensor{4,3});
julia> tovoigt(A);
julia> @time for i in 1:10000
tovoigt(A)
end
0.003383 seconds (20.00 k allocations: 4.730 MiB)
```
> Add type annotations to offdiagscale of tovoigt

- src/voigt.jl
- test/test_ops.jl
You can now do something like
```julia
const abaqus = [1 4 6; 0 2 5; 0 0 3]
tovoigt(A; order=abaqus, offdiagscale=2)
```
cc @terofrondelius
> Enable order kwarg for Voigt ordering.

- Project.toml
- src/constructors.jl
- test/test_misc.jl
Fixes e.g. these cases:
```julia
julia> S = Tensor{2,2}((1, 2, 3, 4));
julia> dev(S)
2×2 Tensor{2,2,Float64,4}:
-0.666667  3.0    
2.0       2.33333
julia> fromvoigt(SymmetricTensor{2,2}, [1,1,1])
2×2 SymmetricTensor{2,2,Float64,3}:
1.0  1.0
1.0  1.0
julia> Tensor{2,2}((true, 2, 3.0, Float32(4)))
2×2 Tensor{2,2,Float64,4}:
1.0  3.0
2.0  4.0
```
So now you can use integer tensors @KimAuth :stuck_out_tongue:
> Add some constructors for heterogeneous tuples

- Project.toml
- src/Tensors.jl
- src/voigt.jl
- test/F64.jl
- test/test_misc.jl
These changes should allow to use symbolic numbers such as `Sym` from `SymPy.jl` within `Tensors.jl` .
> Allows use of symbolic tensors

- src/Tensors.jl
- test/test_misc.jl
``` julia
a = rand(SymmetricTensor{2,3})
b = typeof(a)((i,j)-> i==j ? 1.0 : 0.0)
```
did not work before this change was added. 
However, for some unknown reason, 
``` julia
a = rand(Tensor{2,3})
b = typeof(a)((i,j)-> i==j ? 1.0 : 0.0)
```
still fails (also causing the new tests to fail)
> Construct from fully specified

- src/symmetric.jl
- test/test_ops.jl
The right formula for "minorsymmetrization" is `(Sᵢⱼₖₗ+Sⱼᵢₖₗ+Sᵢⱼₗₖ+Sⱼᵢₗₖ)/4` and not `(Sᵢⱼₖₗ+Sⱼᵢₖₗ+Sᵢⱼₖₗ+Sᵢⱼₗₖ)/4`
> Correction of bug in minorsymmetric

- docs/src/man/automatic_differentiation.md
- src/Tensors.jl
- src/automatic_differentiation.jl
- src/tensor_products.jl
- test/test_ad.jl
This PR considers creating a mechanism for inserting a known derivative into a function that is part of a chain of functions differentiated using the `Tensors.jl`'s `gradient` method. ~~The new method is `insert_gradient`, and `extract_value` has also been exported.~~ Using the suggestion from @KristofferC below, it introduces the macro `@implement_gradient` 
The main goal is to be able to provide analytical derivatives when automatic differentiation fails, see e.g. #174 .
As a side benefit, if a known analytical derivative of part of a function that is slow to call using dual numbers, this method can be used to provide a more efficient implementation (not the case for most functions in `Tensors.jl` though)
Updated example (cases in a comment below are outdated, see also docs):
```julia …
```
> Enable insertion of known derivative in autodiff chain

- src/math_ops.jl
- test/test_misc.jl
This lets us dispatch to LAPACKs symmetric eigenvalue solver, and also
makes sure that the returned eigentensors are normalized.
> Eigen: Use Mandel representation for 4th order eigen

- Project.toml
- src/Tensors.jl
- src/constructors.jl
- test/test_misc.jl
This restrict the constructors for heterogeneous tuples from https://github.com/Ferrite-FEM/Tensors.jl/pull/131 to
tuples of the correct length. This avoids a stack overflow when passing
tuples of wrong length. Fixes https://github.com/Ferrite-FEM/Tensors.jl/issues/140, https://github.com/Ferrite-FEM/Tensors.jl/issues/141.
> Restrict constructors for heterogeneous tuples

- Project.toml
- src/Tensors.jl
- src/math_ops.jl
- test/F64.jl
- test/test_ops.jl
This patch exports the existing rotation_matrix function, and adds a new method rotation_matrix(x::Number) which returns the two-dimensional rotation matrix for rotation x radians around the out-of-plane axis.
> Export rotation_tensor and add implementation for 2D

- src/basic_operations.jl
- test/test_misc.jl
Results for a few all-zero symmetric tensors where the difference is significant
```julia
SymmetricTensor{2, 3, Float64, 6}: 
16.416 ns (0 allocations: 0 bytes) #master
3.800 ns (0 allocations: 0 bytes) #pr
SymmetricTensor{4, 2, Float64, 9}: 
54.205 ns (0 allocations: 0 bytes) #master
4.700 ns (0 allocations: 0 bytes) #pr
SymmetricTensor{4, 3, Float64, 36}:
245.130 ns (0 allocations: 0 bytes) #master
20.281 ns (0 allocations: 0 bytes) #pr
```
Full code and results:
```julia 
using Tensors, BenchmarkTools
iszero_pr(a::AbstractTensor) = all(iszero, Tensors.get_data(a))
for order in (2,4)
for dim in (1,2,3)
a = zero(Tensor{order,dim})
b = rand(Tensor{order,dim})
as=zero(SymmetricTensor{order,dim})
bs = rand(SymmetricTensor{order,dim})
println("order=$order, dim=$dim")
for t in (a, as, b, bs) …
```
> Faster iszero for symmetric tensors

- src/Tensors.jl
I think this should be the fix for the deprecated syntax?
> VarArg{Any} instead of VarArg{<:Any}

- Project.toml
- docs/Manifest.toml
- src/precompile.jl
This pull request migrates the package from [SnoopPrecompile](https://github.com/timholy/SnoopCompile.jl/tree/master/SnoopPrecompile) to [PrecompileTools](https://github.com/JuliaLang/PrecompileTools.jl).
PrecompileTools is **nearly a drop-in replacement** except that there are **changes in naming and how developers locally disable precompilation** (to make their development workflow more efficient). These changes are described in [PrecompileTool's enhanced documentation](https://julialang.github.io/PrecompileTools.jl/stable/), which also includes instructions for users on how to set up custom "Startup" packages, handling precompilation tasks that are not amenable to workloads, and tips for troubleshooting.
Why the new package? It meets several goals:
- The name "SnoopPrecompile" was …
> Migrate from SnoopPrecompile to PrecompileTools

- src/voigt.jl
Noticed during teaching that there are no docstrings for to/from mandel
> Document tomandel/frommandel

- src/math_ops.jl
Profit from fast + allocation free `StaticArrays` inverses
```julia
julia> A = rand(Tensor{4,3}); Asym = symmetric(A);       
julia> @btime inv($A);                                                                                                                                                                                                                    
1.321 μs (5 allocations: 6.19 KiB) …
```
> Faster inverse of 4th order Tensors

- CHANGELOG.md
- Project.toml
- src/Tensors.jl
- src/automatic_differentiation.jl
- src/constructors.jl
- src/indexing.jl
- src/math_ops.jl
- src/tensor_products.jl
- src/utilities.jl
- test/test_ad.jl
- test/test_misc.jl
- test/test_ops.jl
Start of limited support for 3rd order tensors.
Currently, the aim is just to implement what is required for mapping of Hcurl and Hdiv interpolations in Ferrite (Co- and Contra-variant Piola mapping)
> 3rd order tensors

- CHANGELOG.md
- Project.toml
- src/voigt.jl
- test/test_ops.jl
This broke my code that used to work, where I was doing automatic differentiation but not all tensor elements I wanted to put in my vector were dual numbers.
> Bugfix: tovoigt for different eltype of tensor and vector
